export const RZServicesTree = {
  categories: {
    items: [
      {
        children: [],
        include_in_menu: 1,
        level: 2,
        name: 'Greiðslumátar',
        position: 1,
        uid: '1',
        url_key: 'greioslumatar',
        url_path: 'greioslumatar',
        url_suffix: '/',
      },
      {
        children: [],
        include_in_menu: 1,
        level: 2,
        name: 'Afhendingarmátar',
        position: 1,
        uid: '2',
        url_key: 'afhendingarmatar',
        url_path: 'afhendingarmatar',
        url_suffix: '/',
      },
      {
        children: [],
        include_in_menu: 1,
        level: 2,
        name: 'Verkstæði',
        position: 1,
        uid: '3',
        url_key: 'verkstaedi',
        url_path: 'verkstaedi',
        url_suffix: '/',
      },
      {
        children: [],
        include_in_menu: 1,
        level: 2,
        name: 'Fyrirtækjaþjónusta',
        position: 1,
        uid: '4',
        url_key: 'fyrirtaekjapjonusta',
        url_path: 'fyrirtaekjapjonusta',
        url_suffix: '/',
      },
      {
        children: [],
        include_in_menu: 1,
        level: 2,
        name: 'Ábyrgð',
        position: 1,
        uid: '5',
        url_key: 'abyrg',
        url_path: 'abyrg',
        url_suffix: '/',
      },
      {
        children: [],
        include_in_menu: 1,
        level: 2,
        name: 'Viðbótartrygging',
        position: 1,
        uid: '6',
        url_key: 'vi-botartrygging',
        url_path: 'vi-botartrygging',
        url_suffix: '/',
      },
    ],
  },
};
