---
name: Lint

on: [pull_request]

jobs:
  python_lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5

        with:
          python-version: "3.10"

      - name: Install Project dependencies
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

        run: |
          aws --version
          env
          bash install_rtw.sh -y

          pip install --upgrade pip
          pip install build
          pip install .
          pip install teroshop[core]
          pip install teroshop[dev]

      - name: Analysing the code with mypy
        run: |
          mypy -p teroshop --show-error-codes

      - name: Analysing the code with flake8
        run: |
          flake8 teroshop --count --show-source --statistics
